### ISSUE TITLE
Link to `plink` in README is broken

### ISSUE THREAD

**Issue by bradschwartz** [benknoble/Dotfiles#134]
Under the `Installing` Header, this link goes nowhere: https://github.com/benknoble/Dotfiles/blob/master/plink

**Comment by benknoble** [comment]
Hm. The markdown there is `[plink](./plink/)`, which is normally enough to link to files in the repo. Probably this doesn't work because that directory is a submodule (clicking takes you to a tree of https://github.com/benknoble/plink).

I'll just make that link point to the project, though I'm planning on replacing Plink soon, probably.
